esphome:
  name: filament-dryer
  friendly_name: Сушилка филамента
  on_boot:
    priority: 600
    then:
      - script.execute: control_loop

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

network:
  enable_ipv6: true

openthread:
  device_type: FTD
  tlv: !secret thread_tlv

i2c:
  id: dikale_i2c
  sda: GPIO19
  scl: GPIO20
  scan: True
  frequency: 400kHz

output:
  - platform: ledc
    pin: GPIO7
    id: fan_pwm_output
    frequency: 25000Hz

fan:
  - platform: speed
    output: fan_pwm_output
    name: "Вентилятор сушилки"
    id: dryer_fan
    internal: true

globals:
  - id: is_heating  # Гистерезис нагрева
    type: bool
    initial_value: 'false'

  - id: current_page
    type: int
    initial_value: '0'
  - id: menu_index
    type: int
    initial_value: '0'
  - id: last_activity_time
    type: uint32_t
    initial_value: '0'

switch:
  - platform: template
    name: "Сушилка филамента"
    id: system_power
    icon: "mdi:power"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
#    turn_on_action:
#      - script.execute: activity_trigger
    turn_off_action:
      - switch.turn_off: heater_switch
      - fan.turn_off: dryer_fan

  - platform: template
    name: "Режим работы"
    id: mode_temp_control
    icon: "mdi:thermometer-check"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
#    turn_on_action:
#      - script.execute: activity_trigger
#    turn_off_action:
#      - script.execute: activity_trigger

  - platform: gpio
    id: heater_switch
    internal: true
    pin:
      number: GPIO8
      inverted: true
      mode:
        output: True
        open_drain: True

number:
  - platform: template
    name: "Целевая влажность"
    id: target_humidity
    unit_of_measurement: "%"
    min_value: 10
    max_value: 90
    step: 1
    initial_value: 40
    restore_value: true
    optimistic: true
#    set_action:
#      - script.execute: activity_trigger

  - platform: template
    name: "Целевая температура"
    id: target_temp
    unit_of_measurement: "C"
    min_value: 20
    max_value: 80
    step: 1
    initial_value: 50
    restore_value: true
    optimistic: true
#    set_action:
#      - script.execute: activity_trigger

  - platform: template
    name: "Яркость экрана"
    id: display_brightness
    entity_category: config
    unit_of_measurement: "%"
    min_value: 10
    max_value: 100
    step: 10
    initial_value: 80
    restore_value: true
    optimistic: true
#    on_value:
#      then:
#        - lambda: 'id(display_1306).set_contrast(x / 100.0);'
#        - script.execute: activity_trigger

  - platform: template
    name: "Отключение"
    id: display_timeout
    entity_category: config
    unit_of_measurement: "min"
    min_value: 0.5
    max_value: 5
    step: 0.5
    initial_value: 1
    restore_value: true
    optimistic: true
#    set_action:
#      - script.execute: activity_trigger

sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      id: temp_sensor
      name: "Температура"
    humidity:
      id: humidity_sensor
      name: "Влажность"
    update_interval: 60s

  - platform: rotary_encoder
    id: my_encoder
    pin_a: GPIO2
    pin_b: GPIO1
    on_clockwise:
#      - script.execute: activity_trigger
      - lambda: |-
          int p = id(current_page);
          if (p == 0) {
            id(system_power).turn_on();
          } else if (p == 1) {
            if (id(menu_index) < 4) id(menu_index)++;
          } else {
            // МЕНЯЕМ ЗНАЧЕНИЯ (Страницы 2, 3, 5, 6)
            if (p == 2) id(target_temp).make_call().set_value(id(target_temp).state + 1).perform();
            if (p == 3) id(target_humidity).make_call().set_value(id(target_humidity).state + 1).perform();
            if (p == 4) id(mode_temp_control).turn_on();
            if (p == 5) id(display_brightness).make_call().set_value(std::min(100.0f, id(display_brightness).state + 10.0f)).perform();
            if (p == 6) id(display_timeout).make_call().set_value(std::min(60.0f, id(display_timeout).state + 1.0f)).perform();
          }
    on_anticlockwise:
#      - script.execute: activity_trigger
      - lambda: |-
          int p = id(current_page);
          if (p == 0) {
            id(system_power).turn_off();
          } else if (p == 1) {
            if (id(menu_index) > 0) id(menu_index)--;
          } else {
            if (p == 2) id(target_temp).make_call().set_value(id(target_temp).state - 1).perform();
            if (p == 3) id(target_humidity).make_call().set_value(id(target_humidity).state - 1).perform();
            if (p == 4) id(mode_temp_control).turn_off();
            if (p == 5) id(display_brightness).make_call().set_value(std::max(10.0f, id(display_brightness).state - 10.0f)).perform();
            if (p == 6) id(display_timeout).make_call().set_value(std::max(1.0f, id(display_timeout).state - 1.0f)).perform();
          }

binary_sensor:
  - platform: gpio
    pin: {number: GPIO3, mode: INPUT_PULLUP, inverted: true}
    id: encoder_button
    on_multi_click:
      # КОРОТКОЕ НАЖАТИЕ
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.1s
        then:
#          - script.execute: activity_trigger
          - lambda: |-
              if (id(current_page) == 0) {
                id(current_page) = 1;
              } else if (id(current_page) == 1) {
                // menu_index 0 (TEMP) -> page 2
                // menu_index 1 (HUMI) -> page 3
                // menu_index 2 (MODE) -> page 4
                // menu_index 3 (BRIGHT) -> page 5
                // menu_index 4 (TIMEOUT) -> page 6
                id(current_page) = id(menu_index) + 2;
              } else {
                id(current_page) = 1; // Из настроек назад в меню
              }

      # ДОЛГОЕ НАЖАТИЕ: Выход домой (если в меню) или Вкл/Выкл (если дома)
      - timing:
          - ON for at least 1s
        then:
#          - script.execute: activity_trigger
          - lambda: |-
              if (id(current_page) > 0) {
                id(current_page) = 0; // Выход на главный экран из любого места
              } else {
                id(system_power).toggle(); // Вкл/выкл сушилку, если мы уже дома
              }

script:
#  - id: activity_trigger
#    then:
#      - lambda: |-
#          id(last_activity_time) = millis();
#          // При любом действии восстанавливаем яркость из настроек
#          id(display_1306).set_contrast(id(display_brightness).state / 100.0);

  - id: control_loop
    mode: restart
    then:
      - while:
          condition:
            lambda: 'return true;'
          then:
            - if:
                condition:
                  - switch.is_on: system_power
                then:
                  - lambda: |-
                      float current_t = id(temp_sensor).state;
                      float target_t = id(target_temp).state;
                      float hysteresis = 5.0; // Порог в 5 градусов
                      if (current_t < (target_t - hysteresis)) {
                        id(is_heating) = true;
                      } else if (current_t >= target_t) {
                        id(is_heating) = false;
                      }

                  - if:
                      condition:
                        lambda: 'return id(is_heating);'
                      then:
                        - fan.turn_on:
                            id: dryer_fan
                            speed: 100
                        - switch.turn_on: heater_switch
                      else:
                        - fan.turn_on:
                            id: dryer_fan
                            speed: 50
                        - switch.turn_off: heater_switch
                else:
                  # Если система выключена кнопкой
                  - fan.turn_off: dryer_fan
                  - switch.turn_off: heater_switch
                  - lambda: 'id(is_heating) = false;'
            - delay: 5s
